# Generated by Django 5.1.6 on 2025-04-15 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('connect_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('initiator_user_id', models.UUIDField()),
                ('connection_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('connection_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('privacy_setting', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], max_length=15)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('saved', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='post_audio/')),
                ('text', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('queued', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.IntegerField(default=0)),
                ('challenge_track_id', models.UUIDField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('friend_user_id', models.UUIDField()),
                ('accepted', models.BooleanField(default=False)),
                ('requested', models.BooleanField(default=True)),
                ('friendship_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'friend_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('type', models.CharField(choices=[('like', 'Like'), ('love', 'Love')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
        ),
    ]
