# Generated by Django 5.1.6 on 2025-07-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
