# Generated by Django 5.1.6 on 2025-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='accepted_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
