# Generated by Django 5.1.6 on 2025-07-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interest_profile_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audioUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
