# Generated by Django 5.1.6 on 2025-07-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interest_profile_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
