# Generated by Django 5.1.6 on 2025-03-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_photo_useraccount_profilepicture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='profilePicture',
            new_name='profilepicture',
        ),
    ]
