# Generated by Django 5.1.6 on 2025-06-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_interest',
                'managed': False,
            },
        ),
    ]
