# Generated by Django 5.1.6 on 2025-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
