# Generated by Django 5.1.6 on 2025-04-15 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('source_user_id', models.UUIDField()),
                ('type', models.CharField(choices=[('friend_request', 'Friend Request'), ('message', 'Message'), ('challenge_completion', 'Challenge Completion'), ('reaction', 'Reaction')], max_length=25)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
