# Generated by Django 5.1.6 on 2025-08-09 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinterest',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinterests', to='connect_app.interest'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinterests', to='connect_app.useraccount'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('userId', 'interestId')},
        ),
        migrations.CreateModel(
            name='InstantInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_users', to='connect_app.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_interests', to='connect_app.useraccount')),
            ],
            options={
                'managed': True,
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
