# Generated by Django 5.1.6 on 2025-04-15 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.UUIDField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=10)),
                ('encrypted_conversation', models.TextField(blank=True, null=True)),
                ('delete_settings', models.JSONField(blank=True, null=True)),
                ('admin', models.UUIDField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message1to1',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.UUIDField()),
                ('receiver', models.UUIDField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('encrypted_conversation', models.TextField(blank=True, null=True)),
                ('delete_settings', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reply_to_message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message1to1')),
            ],
        ),
    ]
