# Generated by Django 5.1.6 on 2025-06-22 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('aim', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('salt', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('last_login_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_useraccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='chat_groups', to='message.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.chatgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to='message.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.groupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_to_receiver', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_one_to_one', to='message.useraccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_one_to_one', to='message.useraccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='message1to1',
            name='reply_to_message_id',
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='delivered_to',
            field=models.ManyToManyField(blank=True, related_name='delivered_group_messages', through='message.MessageDelivery', to='message.useraccount'),
        ),
        migrations.DeleteModel(
            name='Message1to1',
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['message'], name='message_mes_message_ac0914_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['user'], name='message_mes_user_id_48415d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagedelivery',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='onetoonemessage',
            index=models.Index(fields=['receiver'], name='message_one_receive_64d17a_idx'),
        ),
        migrations.AddIndex(
            model_name='onetoonemessage',
            index=models.Index(fields=['sent_to_receiver'], name='message_one_sent_to_8eef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='onetoonemessage',
            index=models.Index(fields=['receiver', 'sent_to_receiver'], name='message_one_receive_99a62a_idx'),
        ),
    ]
